### PR TITLE
Changed bug tracker for the official forum

### PR DESCRIPTION
**Pull request by NameLessGO**

### CODE REVIEW

**Comment by NameLessGO** [comment]
What happened?

**Comment by NameLessGO** [comment]
Bot build

**Comment by ingemarberg** [comment]
I'm sorry for the late reply. I'll gladly merge this, but the pull request needs to be updated first. Please make sure to use _Update with rebase_.

**Comment by NameLessGO** [comment]
Sorry about the mistake, this is my first PL being done xD, Thanks for maintaining Anki on FlatHub

**Comment by ingemarberg** [comment]
No worries! I should be the one to apologize. Once again, sorry for the late reply. Anyway, this looks good to me so I'll go ahead and merge it now. This should close #77 as well.

Thank you for contributing!

**Pull request merged**
