### PR TITLE
Update to version 2.1.3

### PR DESCRIPTION
**Pull request by mliertzer**
Version 2.1.3 requires python 3.6, that latest version of which (3.6.6) is now included as a dependency.
I updated all dependencies to the latest version found in pypi and cleaned up the build commands reflecting the latest changes in the upstream Makefile.

### CODE REVIEW

**Comment by mliertzer** [comment]
Pull-request updated, HEAD is now 0b72ed24f405d1de5a6d6e7dd464a31645fff91a

**Comment by mliertzer** [comment]
Pull-request updated, HEAD is now 9be2ef2a0e68ac715be5ce3a044e93d1b58e67a3

**Comment by jurf** [comment]
Looks fine by me. I’ll maybe give this a test run in the afternoon, would love a working properly working Anki on Flathub.

**Comment by dsd** [comment]
Sorry that I missed this before doing a quick update to 2.1.4 at the end of last week.

Rather than bundle py3.6 I think I'd rather battle along with Python 3.5 and then switch to an updated KDE runtime which looks like it should be available soon (including Python 3.6), assuming the new Qt version does not give us difficulties.

If there are still other changes you see as worthwhile then feel free to update the pull request! Thanks.

**Comment by jurf** [comment]
OK, well, seeing that master is already on 2.1.5 and (if I read the diff correctly) all the other fixes should already be present, I’ll close this, but still, thanks a lot!

**Pull request closed without merging**
