### PR TITLE
(Review) Update 23.10.1

### PR DESCRIPTION
**Pull request by NameLessGO**
Should be ok, but please check!

### CODE REVIEW

**Comment by NameLessGO** [comment]
Build

**Comment by NameLessGO** [comment]
Forgot about

`The Linux Qt6 build requires a newer glibc, so older distros like Debian 11 won't work with it.`

don't merge yet

**Comment by teynav** [comment]
https://github.com/ankitects/anki/commit/129e01a631d709c740d4d7b664b6bb2f6317928d

This commits bumps PyQt requirements on Linux to Qt 6.6

Reading the documentation here: 

https://doc.qt.io/qt-6/supported-platforms.html

> Note: Linux binary packages are linked against glibc 2.28. If you are using a glibc version older than that you need to build Qt from sources or upgrade glibc to 2.28 or newer.

**Comment by rayes0** [comment]
Merged in #122

**Pull request closed without merging**
