### PR TITLE
Update runtime to 23.08

### PR DESCRIPTION
**Pull request by Zishan-Rahman**

### CODE REVIEW

**Comment by Zishan-Rahman** [comment]
```bash
    "warnings": [
        "finish-args-contains-both-x11-and-wayland"
    ]
```

Looks like I'll need to add an exception to [flatpak-builder-lint](https://github.com/flathub/flatpak-builder-lint) for this app.

**Comment by Zishan-Rahman** [comment]
> ```shell
>     "warnings": [
>         "finish-args-contains-both-x11-and-wayland"
>     ]
> ```
> 
> Looks like I'll need to add an exception to [flatpak-builder-lint](https://github.com/flathub/flatpak-builder-lint) for this app.

Looks like I _**won't**_ need to do that, because there's a bug in flatpak-builder-lint that's causing this error: flathub/flatpak-builder-lint#183

Once that's fixed, I'll have the test Flatpak rebuilt, and, hopefully, the test build should succeed.

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
what's the justification for having both?

**Comment by hfiguiere** [comment]
then you should disable wayland if it doesn't work out of the box.
otherwise that's what 'fallback-x11' is for.

**Comment by Zishan-Rahman** [comment]
> then you should disable wayland if it doesn't work out of the box.
> otherwise that's what 'fallback-x11' is for.

@hfiguiere (sorry for the ping) I just took out the X11 socket from `finish-args` and used `fallback-x11` instead, as per your suggestion. Hopefully this should be good to go now :+1:

**Comment by rayes0** [comment]
bot, build

**Pull request merged**
