### PR TITLE
wip: build from source

### LINKED ISSUE #125: Anki on aarch64 is terribly out of date
The flathub website [claims](https://flathub.org/apps/net.ankiweb.Anki) that Anki is on version 23.10, however, this is only true for the x86 version. The aarch64 package is still on version 2.1.15, and hasn't been updated in 4 years! It is so out of date in fact, that it doesn't run properly in wayland, even when setting the appropriate environment variables. It just crashes, given that anki [supports wayland](https://docs.ankiweb.net/platform/linux/wayland.html) only since version 2.1.48. But even without these issues it doesn't work properly.

Please keep the aarch packages up to date.

### PR DESCRIPTION
**Pull request by rayes0**
closes #125, #162
obseletes #32, #31, #17, #163

### CODE REVIEW

**Comment by nehemiagurl** [comment]
it seems that on KDE anki is opened as a generic Wayland window titled "python". pinning anki to the task manager doesn't change much, the window will just appear side by side with the shortcut.
Screenshot_20241129_235519
this is not really an issue with running the Anki beta from pyenv, so i do wonder what's different.

**Comment by n3thshan** [comment]
@nehemiagurl here's a workaround: https://youtu.be/Sungl8gWU_8?si=_foyH8Z1mI0eiYUR&t=129

**Comment by rayes0** [comment]
@nehemiagurl  Looks like something similar to #154, which I cannot debug because I neither daily drive KDE nor have not been able to reproduce it. Looks like this on my kde:

image

Probably look there for more guidance, I am not sure if there is anything I can do in the flatpak to fix this, seems something to do with kde not being able to resolve the app id correctly.

**Comment by nehemiagurl** [comment]
well, the issue seems to have resolved itself after a restart. might have just been an issue switching from the old pyenv shortcut to the flatpak shortcut :woman_shrugging: 
thanks for the tip though @n3thshan , i've used it to fix another application!

**Pull request merged**
