### PR TITLE
WIP: Enable cut-down PyQt on all platforms

### PR DESCRIPTION
**Pull request by jurf**

### CODE REVIEW

**Comment by jurf** [comment]
bot, build

**Comment by jurf** [comment]
bot, build

**Comment by darkdragon-001** [comment]
I couldn't neither access the build log, nor do I know from which source it installs dependencies.

Nevertheless, it looks like [PyQt5 is not available from wheel for ARM](https://github.com/spyder-ide/spyder/issues/6178). Is it possible to install [from source](https://www.riverbankcomputing.com/software/pyqt/download5) directly?
If the problem is already at installing Qt, did you have a look at the base apps [QtWebKit](https://github.com/flathub/io.qt.qtwebkit.BaseApp) and [QtWebEngine](https://github.com/flathub/io.qt.qtwebengine.BaseApp)?

**Comment by jurf** [comment]
No, this is old, and due to a still-unfixed upstream bug. I think it can be worked-around somehow, but I haven’t found the time yet.

And yes, I do know the baseapps. A bit too well. :| I currently have several gigabytes worth of failed pyqtwebengine builds on my machine.

Anyway, if you’re curious about the logs, I’ll run the build again for you:

**Comment by jurf** [comment]
bot, build

**Comment by darkdragon-001** [comment]
The Anki sources moved to https://github.com/ankitects/anki/releases. So 2.1.11 can be found at https://github.com/ankitects/anki/archive/2.1.11.tar.gz

**Comment by jurf** [comment]
I know. I have made several attempts to build them. If you want, try it yourself.

**Pull request closed without merging**
