### PR TITLE
Update Anki to 2.1.50

### LINKED ISSUE #37: fcitx stopped working on the latest version
`fcitx 4.2.9.7-3`
`flatpak Anki 2.1.33`

It used to work before, and now it doesn't acknowledge it exists, even with overrides.

### LINKED ISSUE #42: Typing in Korean shows up in English
Flathub Anki does not allow me to type in Korean.

1. select any input area in Anki
2. change the input method to Korean
3. type anything
4. Korean characters should show up, but instead English characters do

Maybe this issue affects CJK characters in general?

### LINKED ISSUE #56: Typing in Japanese shows up in English
Flathub Anki does not allow me to type in Japanese.

- select any input area in Anki
- change the input method to Japanese
- type anything
- Japanese characters should show up, but instead English characters do

Other applications on my Debian 11 install with fcitx5 mozc work as expected and support Japanese input.

### PR DESCRIPTION
**Pull request by ingemarberg**
This pull request updates Anki to the most recent version. Kerberos 5 seems to be a new dependency, so I've added that as well as `x-checker-data` metadata for use with `flatpak-external-data-checker`. Support for Wayland and IBus has also been added, since there are reports of those working.

I've built and tested this version Anki locally and it seems to work as expected. There are however quite a few changes so someone else should probably test it as well. I've not been able to test Wayland or IBus.

Anki 2.1.50 comes bundled with Fcitx4 and Fcitx5 support, which means that one can finally type in Japanese using Fcitx as well. This should close #37, close #42 and close #56.

### CODE REVIEW

**Comment by rayes0** [comment]
Is there a reason for not using the qt6 version?

**Comment by rayes0** [comment]
Oh, I guess Qt5 is better for maintaining compatibility with add-ons. Although the Qt6 version does come with some Qt5 compatibility shims (see https://github.com/ankitects/anki/pull/1440), but when I tested a Qt6 build it seems some add-ons still don't work.

**Comment by yue-dongchen** [comment]
Do builds on Flathub expire? The flatpakref uri returns 404.

**Comment by ingemarberg** [comment]
@yue-dongchen I think that the test builds only are accessible for a few days at most. I'll ask the bot to build Anki again.

**Comment by ingemarberg** [comment]
bot, build

**Pull request merged**
