### PR TITLE
Updated org.kde.Platform runtime version to "5.15-21.08" (fcitx5 support).

### PR DESCRIPTION
**Pull request by JayXT**

### CODE REVIEW

**Comment by dsd** [comment]
Sorry for the delay in getting to this. Have you tested this, does the app still work, does it help the fcitx situation?

**Comment by JayXT** [comment]
@dsd , no problem, in the end I came to conclusion that most likely this change won't fix the issue. The actual fix should be done on Anki side as is described in this forum thread: https://forums.ankiweb.net/t/add-fcitx5-support/16477/7.
So it's up to debate whether runtime update should be merged or not.

**Comment by dsd** [comment]
Updating to a newer runtime makes sense as a standard maintenance activity. Just want to check that there has been some basic testing that the app still works after this change.

**Comment by JayXT** [comment]
I suppose it works, but I don't have opportunity to test this right now.

**Comment by rayes0** [comment]
Closing as the Anki flatpak no longer uses the KDE runtime.

**Pull request closed without merging**
