### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jurf**
Not to be as a direct criticism, but these manifests were a… well, ahem, (mess.).

A port to YAML would help, but all in its time.

Anki itself is quite cleaned up, but other modules need some TLC too.

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by jurf** [comment]
Done.

**Comment by jurf** [comment]
bot, build

**Comment by jurf** [comment]
(Review welcome.)

**Comment by jurf** [comment]
Actually, back to WIP, got a nice slimdown of PyQt in the works, considerably speeds up build times.

**Comment by dsd** [comment]
Thanks for this! I would prefer it if you could squash all the stylistic changes and renames into a single commit, which introduces no behavioural change.

Then have other individual commits (including explanatory commit messages) for the things that actually cause changes in the output - module updates, cleanup path changes, icon change, PyQt slimdown, etc.

I was unaware that you can do flatpaks in yaml, if that's a norm on flathub then I'd welcome that too.

**Comment by jurf** [comment]
Not a norm, but it’s so much nicer to write/read YAML, and you can have pretty comments too.

> Thanks for this! I would prefer it if you could squash all the stylistic changes and renames into a single commit, which introduces no behavioural change.
> 
> Then have other individual commits (including explanatory commit messages) for the things that actually cause changes in the output - module updates, cleanup path changes, icon change, PyQt slimdown, etc.

Hm, sorry, I got a bit carried away. 😛 I’ll see what I can do.

**Pull request closed without merging**
