### PR TITLE
Update runtime to KDE 5.12, Anki to 2.1.8

### PR DESCRIPTION
**Pull request by jurf**
Also update PyQt, since we now have a higher Qt version available.

### CODE REVIEW

**Comment by jurf** [comment]
@aleixpol hm, could this be a fault in the SDK?

**Comment by aleixpol** [comment]
> @aleixpol hm, could this be a fault in the SDK?

Could be, I have successfully built several packages already though.

**Comment by jurf** [comment]
testbot, build

**Comment by jurf** [comment]
bot, build

**Comment by jurf** [comment]
bot, build

**Pull request merged**
