### PR TITLE
Switch to KDE runtime, fix GNOME decorations

### PR DESCRIPTION
**Pull request by maggster165**

### CODE REVIEW

**Comment by rayes0** [comment]
What is the rationale behind switching to the kde runtime? Anki bundles its own QT so it is not needed I believe.

**Comment by maggster165** [comment]
The main reason for this are window decorations outside of KDE. Using the KDE runtime bundles the flatpak with the necessary decorations for other Wayland based DEs.
Here is a before and after in GNOME 
image-77
image-64

**Comment by rayes0** [comment]
bot, build

**Comment by rayes0** [comment]
It may bloat the app for only cosmetic benefits, but most users might have the kde runtime already installed, so lets see. In the future, I am planning on building the app from scratch which would fix this. ref: #162

**Comment by rayes0** [comment]
Thanks for working on this. Most users will have the runtime installed, so this is acceptable temporarily. I am going to merge this until the new build system is set up.

**Comment by rayes0** [comment]
bot, build

**Comment by sommerluk** [comment]
I've tested it in KDE because I was hoping with the KDE runtime we get finally native KDE widget style (Breeze) in Anki. However, even when selecting "Native" as widget style, I still do not get Breeze widget theme:

grafik

**Pull request closed without merging**
