### PR TITLE
Update Anki to 2.1.44, update dependencies, add LaTeX support

### LINKED ISSUE #39: Cannot use LaTeX
This flatpaked version of Anki cannot create cards using LaTeX.

For example create a card with a field containing
`[$]x=0[/$]`

will result in an error message

    Error executing latex.
    Generated file: /var/tmp/anki_temp/tmp.tex
    Have you installed latex and dvipng/dvisvgm?

Importing decks where the LaTeX notes are already processed to images does work.

So, does anyone have an idea of how to enable LaTeX in this flatpak?
Thanks for your help!

### PR DESCRIPTION
**Pull request by ingemarberg**
This pull request updates Anki, mpv and libass to their most recent version. It also adds support for LaTeX using the Flatpak extension org.freedesktop.Sdk.Extension.texlive, which should close #39.

### CODE REVIEW

**Comment by laolux** [comment]
Works well for me. LaTeX now works, too, thanks a lot for that!

**Comment by dsd** [comment]
Thank you. Please feel free to apply to become a maintainer if you would like to push such updates directly in future.

**Comment by ingemarberg** [comment]
Thanks for merging my pull request, @dsd! I could probably help maintain the Anki Flatpak for the time being. Where would I apply? I've looked at the Flathub documentation but couldn't find something that mentioned this.

**Comment by dsd** [comment]
@nedrichards Hi, could you please add ingemarberg as an additional maintainer of this flatpak. Thanks

**Comment by kowalcj0** [comment]
Hi @ingemarberg ,
Adding `texlive` dependency means that flatpak Anki users have to apparently download an additional 4.3GB package.
See https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/51
Is that necessary?
Thanks

**Comment by hfiguiere** [comment]
You could add `no-autodownload: true` to the `add-extension` property this would make it optional.

**Comment by ingemarberg** [comment]
I agree that adding `no-autodownload: true` would be a better solution, especially since there might be many users that have no need for this extension. Somehow I assumed this would be the default case. Thanks for pointing out my mistake. I've made a new pull request that should fix this.

**Comment by ingemarberg** [comment]
@kowalcj0 - This should be fixed in #48. I've tried installing the test build and `org.freedesktop.Sdk.Extension.texlive` is not downloaded automatically anymore. I don't have write access so I can't merge it myself.

@hfiguiere - Thanks for letting me know how this could be resolved!

Thanks once again for pointing out my mistake. I'm still very new to contributing to open source, so I'm sorry I didn't catch this before making my first pull request.

**Comment by hfiguiere** [comment]
It was easier than actually argue why the flatpak is 4.3GB when upstream is ~4GB.

**Pull request merged**
